// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// LngLat comma-separated longitude and latitude coord
type LngLat = string

// Route defines model for Route.
type Route struct {
	// Destination comma-separated longitude and latitude coord
	Destination LngLat `json:"destination"`

	// Distance distance from source to destination in meters
	Distance float32 `json:"distance"`

	// Duration time from source to destination in seconds
	Duration float32 `json:"duration"`
}

// Routes defines model for Routes.
type Routes struct {
	Routes []Route `json:"routes"`

	// Source comma-separated longitude and latitude coord
	Source LngLat `json:"source"`
}

// FindRoutesParams defines parameters for FindRoutes.
type FindRoutesParams struct {
	Src LngLat   `form:"src" json:"src"`
	Dst []LngLat `form:"dst" json:"dst"`
}
